### PR TITLE
#167727298 Integrate HoundCI 

### PR DESCRIPTION
**Pull request by stepheng323**
### What does this PR do?
This PR integrates HoundCI to the repository and add a read me badge

### Description of Task to be completed?

- Have a reviewed by Hound badge in the readme

- HoundCI will now add comments to pull request

### How should this be manually tested?

- This should be merged to the default branch

- Once merged, HoundCI will start commenting and reviewing PR request

### Any background context you want to provide?

- By default, HoundCI uses JShint to lint code, but here ESlint will do the job from the rules set in .eslintrc file

### What are the relevant pivotal tracker stories?

- #167727298

### CODE REVIEW

**Comment by stepheng323** [comment]
Mistakenly, push the create PR request when, i am not done with the PR description

**Comment by stepheng323** [comment]
#### What does this PR do?
This PR integrates HoundCI to the repository and add a read me badge
#### Description of Task to be completed?
Have a reviewed by Hound badge in the readme
HoundCI will now add comments to pull request
#### How should this be manually tested?
This should be merged to the default branch
 Once merged, HoundCI will start commenting and reviewing PR request
#### Any background context you want to provide?
By default, HoundCI uses JShint to lint code, but here ESlint will do the job from the rules set in .eslintrc file
#### What are the relevant pivotal tracker stories?
#167727298

**Comment by shonubijerry** [comment]
I think this just does it.

**Review by jsamchineme — APPROVED** [review]

**Review by shonubijerry — APPROVED** [review]
Nice one, it's okay to merge.

**Pull request merged**
