### PR TITLE
#167727297 Setup Configuration for ES-lint

### PR DESCRIPTION
**Pull request by orley12**
#### What does this PR do?

- Setup Configuration for ES-lint

#### Description of Task to be completed?

- Configure ES-Lint

#### How should this be manually tested?

- Clone the repository, cd into it , and  run **npx eslint ./**

#### Any background context you want to provide?

- You might need to install ES-Lint dependency to test this out

#### What are the relevant pivotal tracker stories?

- [#167727297](https://www.pivotaltracker.com/story/show/167727297)

#### Questions:

- Are there other additions to this setup

### CODE REVIEW

**Comment by stepheng323** [comment]
Solid ESlint configuration, all the required rules were added and the .eslintrc was in JSON which is the extension needed for HoundCI to lint our PR, however, in the future, there might be folders that we will want ESlint to ignore E.G the build folder (ES5 syntax), it will be nice if there is a .eslintignore file that tells ESlint what folder or file to ignore. if you need help with that,  you can check [Here](https://stackoverflow.com/questions/42250257/disable-eslint-rules-for-folder). Nice Job.

**Comment by orley12** [comment]
> Solid ESlint configuration, all the required rules were added and the .eslintrc was in JSON which is the extension needed for HoundCI to lint our PR, however, in the future, there might be folders that we will want ESlint to ignore E.G the build folder (ES5 syntax), it will be nice if there is a .eslintignore file that tells ESlint what folder or file to ignore. if you need help with that, you can check [Here](https://stackoverflow.com/questions/42250257/disable-eslint-rules-for-folder). Nice Job.

Thank you @stepheng323 and also thank you for the resource i will push the implementation  once i am able to rebase @joaquinto merge.

**Review by joaquinto — APPROVED** [review]
Nice job. This looks very good.

**Comment by orley12** [comment]
> Solid ESlint configuration, all the required rules were added and the .eslintrc was in JSON which is the extension needed for HoundCI to lint our PR, however, in the future, there might be folders that we will want ESlint to ignore E.G the build folder (ES5 syntax), it will be nice if there is a .eslintignore file that tells ESlint what folder or file to ignore. if you need help with that, you can check [Here](https://stackoverflow.com/questions/42250257/disable-eslint-rules-for-folder). Nice Job.

i have applied your suggestion.

**Comment by stepheng323** [comment]
Nice one there

**Review by stepheng323 — APPROVED** [review]

**Review by jsamchineme — APPROVED** [review]

**Pull request merged**
